### ISSUE TITLE
The analyzeCommits plugin must return a valid semver release type. The valid values are: patch, minor, major.

### ISSUE THREAD

**Issue by jebarpg** [momocow/semantic-release-gitmoji#96]
EANALYZECOMMITSOUTPUT The `analyzeCommits` plugin returned an invalid value. It must return a valid semver release type.
The analyzeCommits plugin must return a valid semver release type. The valid values are: patch, minor, major.

The analyzeCommits function of the semantic-release-gitmoji returned prerelease instead.

We recommend to report the issue to the semantic-release-gitmoji authors, providing the following informations:

    * The semantic-release version: 22.0.12
    * The semantic-release logs from your CI job
    * The value returned by the plugin: prerelease
    * A link to the semantic-release plugin developer guide: https://github.com/semantic-release/semantic-release/blob/master/docs/developer-guide/plugin.md

**Comment by momocow** [comment]
Thank for reporting the issue.

I'm surprised that this bug was actually originated in 2018 but reported in 2024. lol

I found [semantic-release changed their release types at Nov 30, 2018](https://github.com/semantic-release/semantic-release/commit/7b4052470b23261c9e679a17bff034da311fd894#diff-5ca2332ebe61b12a91cf9b8eb3c00a7b22667699fa09d91c931399c14d197d41) while [release types defined in this plugin was committed at Nov 16, 2018](https://github.com/momocow/semantic-release-gitmoji/commit/017f92e92a8cdd5517b094674ddbbd257b571b7e#diff-87c8c110242e5964403277f53835c8f33b195b001b0a31798f94ecb9a0a2f072).

That is, the set of release types used in the plugin was only valid for 2 weeks, but become invalid for the rest of 5 years. lol

**Comment by jebarpg** [comment]
off-topic but, momocow is that like peach cow... in japanese momo is peach.

**Comment by jebarpg** [comment]
Thanks for the quick reply btw :D I'll look forward to closing this issue.

**Comment by momocow** [comment]
Hello, would you mind providing your configs?

The solution to this issue is quite simple, just change `prerelease` to another release level in release rules in your configs.

**Comment by momocow** [comment]
> off-topic but, momocow is that like peach cow... in japanese momo is peach.

Ha ha, you know quite well about Japanese.
I've also heard about it but momocow is nothing about peach, but the sound of cows, aka 'moo'. 😆

Peach cow gives cute impression to me anyway.
